#######################################
# 1) BUILD NGINX (Alpine-based)
#######################################
FROM alpine:latest AS build

ENV NGINX_VERSION={{ nginx_version }}

RUN apk add --no-cache \
    gcc make build-base linux-headers pcre2-dev \
    zlib-dev openssl-dev libmaxminddb-dev gd-dev \
    libxslt-dev wget git

WORKDIR /build

RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    tar -xvf nginx-${NGINX_VERSION}.tar.gz

RUN git clone https://github.com/leev/ngx_http_geoip2_module.git /tmp/geoip2

WORKDIR /build/nginx-${NGINX_VERSION}

RUN ./configure \
    --prefix=/usr/share/nginx \
    --sbin-path=/usr/sbin/nginx \
    --modules-path=/usr/lib/nginx/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/run/nginx.pid \
    --lock-path=/run/nginx.lock \
    --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=nginx \
    --group=nginx \
    --with-compat \
    --with-file-aio \
    --with-threads \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-http_v3_module \
    --with-stream \
    --with-stream_realip_module \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --add-dynamic-module=/tmp/geoip2 \
    --with-cc-opt="-g -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC" \
    --with-ld-opt="-Wl,-z,relro -Wl,-z,now -Wl,--as-needed"

RUN make -j$(nproc) && make install

# Удаляем весь мусор из стадии сборки
RUN rm -rf /tmp/* /var/cache/apk/* /build/nginx-${NGINX_VERSION}.tar.gz

#######################################
# 2) FINAL stage
#######################################
FROM debian:bookworm-slim

# Создаем пользователя и группу nginx
RUN addgroup -S -g 101 nginx && \
    adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx

# Устанавливаем runtime зависимости
RUN apk add --no-cache \
    libmaxminddb \
    gd \
    pcre2 \
    libxslt \
    zlib \
    openssl \
    ca-certificates \
    tzdata \
    curl \
    supervisor \
    bash

# Копируем собранный NGINX
COPY --from=build /usr/sbin/nginx /usr/sbin/nginx
COPY --from=build /usr/lib/nginx /usr/lib/nginx
COPY --from=build /usr/share/nginx /usr/share/nginx
COPY --from=build /etc/nginx /etc/nginx

# Создаем необходимые директории
RUN mkdir -p \
    /etc/nginx/conf.d \
    /etc/nginx/locations \
    /etc/nginx/geolite2 \
    /var/www/html \
    /var/cache/nginx \
    /var/log/nginx \
    /var/log/supervisor \
    /run \
    /docker-entrypoint.d

# Настраиваем права
RUN chown -R nginx:nginx /var/cache/nginx /var/log/nginx && \
    chmod 755 /var/cache/nginx /var/log/nginx

# Перенаправление логов в stdout/stderr
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Копируем файлы конфигурации
COPY mime.types /etc/nginx/
COPY scripts/update_geolite.sh /usr/local/bin/

# Делаем скрипт исполняемым
RUN chmod +x /usr/local/bin/update_geolite.sh

# Копируем конфигурацию supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Копируем конфигурационные файлы для supervisor
COPY supervisor/ /etc/supervisor/conf.d/

# ВАЖНО: скачиваем геобазы прямо при сборке образа
RUN /usr/local/bin/update_geolite.sh

# Cron будет использовать обычный update_geolite.sh
RUN echo "0 */12 * * * root /usr/local/bin/update_geolite.sh >> /var/log/cron.log 2>&1" \
    > /etc/cron.d/geolite-cron && chmod 0644 /etc/cron.d/geolite-cron

# Устанавливаем плавную остановку
STOPSIGNAL SIGQUIT

# Запускаем через supervisor
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"]
